# SELECT CAR_ID, CAR_TYPE, FEE



# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
SELECT CAR_ID, CAR_TYPE, FEE
FROM
(
    SELECT *, DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE CAR_ID
        NOT IN
        (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
            GROUP BY CAR_ID
        )
    ) B
    USING (CAR_ID)
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE)
    HAVING DURATION_TYPE = '30일 이상'
) C
WHERE FEE BETWEEN 500000 AND 2000000
GROUP BY CAR_ID
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC