-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * B.AMOUNT_SUM AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT_SUM FROM FOOD_ORDER WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05 GROUP BY PRODUCT_ID) B
USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

# SELECT * FROM FOOD_PRODUCT
# JOIN (SELECT * FROM FOOD_ORDER WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 05) B
# USING (PRODUCT_ID)
